version: "3.8"

services:
  portfolio:
    build: .
    container_name: new-portfolio
    restart: always
    environment:
      CERTBOT_EMAIL: acenathen.perez@gmail.com
      NGINX_SERVER_NAME: ace-perez-portfolio.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - nginx_certbot_www:/var/www/certbot

volumes:
  nginx_secrets:
  nginx_certbot_www:
