services:
  portfolio:
    build:
      context: .
      dns:
        - 2001:67c:2b0::4
        - 2001:67c:2b0::6
    container_name: new-portfolio
    restart: always
    environment:
      CERTBOT_EMAIL: aceleagueoflegends@gmail.com
      NGINX_SERVER_NAME: ace-perez-portfolio.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - nginx_certbot_www:/var/www/certbot
    networks:
      - portfolio_net
    mem_limit: 256m
    mem_reservation: 128m
    cpus: "0.5"

networks:
  portfolio_net:
    driver: bridge

volumes:
  nginx_secrets:
  nginx_certbot_www:
